### ISSUE TITLE
Not passing through HTML

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-commonmark#24]
If I have a post that contains raw HTML, after passing through CommonMark I get:

```html
<!-- raw HTML omitted -->
```

We need to change the default configuration to prevent this.

**Comment by pathawks** [comment]
We need to enable the `UNSAFE` option to allow HTML passthrough.

**Comment by jekyllbot** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least two months.

The resources of the Jekyll team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a feature request, please consider whether it can be accomplished in another way. If it cannot, please elaborate on why it is core to this project and why you feel more than 80% of users would find this beneficial.

This issue will automatically be closed in two months if no further activity occurs. Thank you for all your contributions.

**Comment by desiredpersona** [comment]
I ran into this issue while benchmarking. 

An include file from my `_includes` directory at the root of my sites source directory stopped working. 

Adding the `UNSAFE` option fixed my issue.

```
# Markdown Settings
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]
```
